name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v2
        with:
          submodules: true  # 检出子模块

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # 指定 PHP 版本

      - name: Install Composer dependencies
        run: |
          cd api
          composer install

      - name: Get latest tag for api
        id: get_api_tag
        run: |
          cd api
          echo "API_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Build frontend
        run: |
          cd frontend
          yarn install
          yarn build

      - name: Get latest tag for frontend
        id: get_frontend_tag
        run: |
          cd frontend
          echo "FRONTEND_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Build admin
        run: |
          cd admin
          yarn install
          yarn build:prod

      - name: Get latest tag for admin
        id: get_admin_tag
        run: |
          cd admin
          echo "ADMIN_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Copy frontend build to api public/doc
        run: |
          mkdir -p api/public/doc
          cp -r frontend/dist/* api/public/doc/

      - name: Copy admin build to api public/admin
        run: |
          mkdir -p api/public/admin
          cp -r admin/dist/* api/public/admin/

      - name: Create a ZIP file of the api
        run: |
          cd api
          zip -r ../release.zip .  # 将 api 目录打包成 zip 文件

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.API_TAG }}  # 使用 api 的最新标签
          release_name: Release ${{ env.API_TAG }}
          body: |
            - Released API version ${{ env.API_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: release.zip
          asset_content_type: application/zip
          
